---
title: "Acerv_YII_CL"
author: "AnaPalacio"
date: "April 26, 2017"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

# General project set-up 

```{r libraries, results="hide"}

getwd()

# Get all libraries and sources required to run the script

library(dplyr)
library(plyr)
library(reshape2)
library(ggplot2)

# Import your data: 
Acer.Tall<-read.csv("Data/YII_2017-09-27_Tall.csv")
Acer.wide<-read.csv("Data/YII_2017-09-27_Wide.csv")
```


# YII over time by temperature

```{r Graphs YII, echo =FALSE}
# YII_Bott <- ggplot(Acer.Tall, aes (Treatment, YII, colour=factor(Time)))
# YII_Bott + stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2)+
#   stat_summary(fun.y=mean, geom="point", size =3, alpha=0.5) +
#   geom_jitter()+
#  facet_wrap(~Time)

YII_Bott <- ggplot(Acer.Tall, aes (Time, YII, colour=factor(Treatment)))
YII_Bott + stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2)+
  stat_summary(fun.y=mean, geom="point", size =3, alpha=0.5) +
# geom_jitter()+
 facet_wrap (~Treatment)

YII_All <- ggplot(Acer.Tall, aes (Time, YII, colour=factor(Treatment)))
YII_All + stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2)+
  stat_summary(fun.y=mean, geom="point", size =3, alpha=0.5) +
   stat_summary(fun.y=mean, geom="line")
 # geom_jitter()+
# facet_grid (~Treatment)


Growth <- ggplot(Acer.growth, aes (Time, Growth, colour=factor(Treatment)))
Growth + stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2)+
  stat_summary(fun.y=mean, geom="point", size =3, alpha=0.5) +
  # geom_jitter()+
 facet_wrap (~Treatment)
```

# YII by fragments over time

```{r GraphsFrag, echo =FALSE}
library(dplyr)
Last.data<-Acer.Tall[which(Acer.Tall$Time==18), ]


Last.data %>% 
  group_by(Treatment) %>% 
  summarise (min_YII = min(YII), max_mpg = max(YII), mean_YII= mean(YII))


YII_Frag <- ggplot(Acer.Tall, aes (Time, YII))
YII_Frag + geom_point() + facet_wrap (~Treatment)

library(lattice)
xyplot(YII ~ Time | Treatment, data=Acer.Tall, type=c("p", "r"), ylim=c(0.0, 0.7))
```

# Fo and Fm over time

```{r Graphs Fo Fm, echo =FALSE}
Fo_Bott <- ggplot(Acer.Tall, aes (Time, F0, colour=factor(Treatment)))
Fo_Bott + stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2)+
  stat_summary(fun.y=mean, geom="point", size =3, alpha=0.5) +
  #geom_jitter()+
 facet_grid (~Treatment)


Fm_Bott <- ggplot(Acer.Tall, aes (Time, Fm, colour=factor(Treatment)))
Fm_Bott + stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2)+
  stat_summary(fun.y=mean, geom="point", size =3, alpha=0.5) +
  #geom_jitter()+
 facet_grid (~Treatment)

```





Stats

```{r StatsForTreattmentandTime}

YII_Bott <- ggplot(Acer.Tall, aes (Time, YII, colour=factor(Treatment)))
YII_Bott + stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2)+
  stat_summary(fun.y=mean, geom="point", size =3, alpha=0.5) +
  stat_summary(fun.y=mean, geom="line")
  # geom_jitter()+


Acer.Tall$Treatment <- as.factor(Acer.Tall$Treatment)
Acer.Tall$Time <- as.factor(Acer.Tall$Time)

library(multcomp)
library(multcompView)
library(lsmeans)


LM_Treatment <- lm(YII ~ Treatment, data= Acer.Tall)

LM_Time <-lm(YII ~ Time, data = Acer.Tall)

LM_Tre_Time <- lm(YII ~ Time * Treatment, data=Acer.Tall)

anova(LM_Treatment)
TukeyHSD(aov(LM_Treatment))

anova(LM_Time)
TukeyHSD(aov(LM_Time))

anova(LM_Tre_Time)
# TukeyHSD(aov(LM_Tre_Time))

#  cld from multicom  set a compact letter display of all pair-wise comparisons.
cld(lsmeans(LM_Treatment, "Treatment"))
cld(lsmeans(LM_Time, "Time"))
cld(lsmeans(LM_Tre_Time, specs = c("Treatment", "Time")))

```

# Changes bt time points 

```{r ChangePerTime, echo =FALSE}
Acer.wide$Change1<-((Acer.wide$YII_1)-(Acer.wide$YII_0))
Acer.wide$Change2<-((Acer.wide$YII_2)-(Acer.wide$YII_1))
Acer.wide$Change3<-((Acer.wide$YII_2)-(Acer.wide$YII_0))


YII_Change1 <- ggplot(Acer.wide, aes (Treatment, Change1, colour=factor(Treatment)))
YII_Change1 + stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2)+
  stat_summary(fun.y=mean, geom="point", size =3, alpha=0.5) +
  geom_jitter()

YII_Change2 <- ggplot(Acer.wide, aes (Treatment, Change2, colour=factor(Treatment)))
YII_Change2 + stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2)+
  stat_summary(fun.y=mean, geom="point", size =3, alpha=0.5) +
  geom_jitter()

YII_Change3 <- ggplot(Acer.wide, aes (Treatment, Change3, colour=factor(Treatment)))
YII_Change3 + stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2)+
  stat_summary(fun.y=mean, geom="point", size =3, alpha=0.5) +
  geom_jitter()

```
